import {
  sqliteTable,
  text,
  integer,
  real,
  uniqueIndex,
  index,
} from "drizzle-orm/sqlite-core";
import { sql } from "drizzle-orm";
import { projects } from "./app.schema";

// ============================================================================
// Content tables — SEO article generation (phase 1) and the headless API.
// See docs/superpowers/specs/2026-07-04-content-articles-design.md
// ============================================================================

// One row per generated article. Created as `queued` before the
// ArticleGenerationWorkflow starts; the workflow moves it to `generating`
// then `draft` (or `failed`). `draft ↔ published` is a user action.
export const contentArticles = sqliteTable(
  "content_articles",
  {
    id: text("id").primaryKey(),
    projectId: text("project_id")
      .notNull()
      .references(() => projects.id, { onDelete: "cascade" }),
    keyword: text("keyword").notNull(),
    locationCode: integer("location_code").notNull().default(2840),
    languageCode: text("language_code").notNull().default("en"),
    status: text("status", {
      enum: [
        "queued",
        "generating",
        "draft",
        "published",
        "failed",
        // Retired by the weekly self-repair pass (dead article, no impressions).
        "archived",
      ],
    })
      .notNull()
      .default("queued"),
    slug: text("slug").notNull(),
    title: text("title"),
    metaDescription: text("meta_description"),
    // E-E-A-T byline, editable in the editor.
    author: text("author"),
    // Full article body (markdown).
    markdown: text("markdown"),
    // JSON: { intent, angle, outline, entities, questions, usage }
    brief: text("brief"),
    // JSON: [{ question, answer }] — FAQ section + FAQPage JSON-LD.
    faq: text("faq"),
    // JSON: SERP URLs used for grounding.
    sourceUrls: text("source_urls"),
    workflowRunId: text("workflow_run_id"),
    error: text("error"),
    // Phase 2/3. `manual` = generated on demand; `autopilot` = generated by
    // the content plan. clusterId (no FK to avoid a circular reference with
    // content_clusters.pillar_article_id) groups an article into a topic
    // cluster for internal linking.
    source: text("source", { enum: ["manual", "autopilot"] })
      .notNull()
      .default("manual"),
    clusterId: text("cluster_id"),
    // When the review window expires and an autopilot draft auto-publishes.
    // Null for manual articles and once published.
    autoPublishAt: text("auto_publish_at"),
    // The article's public URL on the customer's site, derived from the
    // content plan's blog URL pattern. Used as the GSC page filter for
    // per-article performance tracking (phase 3).
    liveUrl: text("live_url"),
    // Last time the weekly GSC self-repair pass processed this article.
    lastRepairedAt: text("last_repaired_at"),
    createdAt: text("created_at")
      .notNull()
      .default(sql`(current_timestamp)`),
    updatedAt: text("updated_at")
      .notNull()
      .default(sql`(current_timestamp)`),
    publishedAt: text("published_at"),
  },
  (table) => [
    uniqueIndex("content_articles_project_slug_idx").on(
      table.projectId,
      table.slug,
    ),
    index("content_articles_project_status_idx").on(
      table.projectId,
      table.status,
    ),
    // Cron scans for autopilot drafts whose review window has expired.
    index("content_articles_auto_publish_idx").on(table.autoPublishAt),
    index("content_articles_cluster_idx").on(table.clusterId),
  ],
);

// ---------------------------------------------------------------------------
// Phase 2 — autopilot: content plan, topic clusters, discovered topic queue.
// ---------------------------------------------------------------------------

// One row per project: the autopilot configuration. When enabled, the cron
// discovers topics, schedules them on a cadence, generates drafts, and
// auto-publishes them after a review window.
export const contentPlans = sqliteTable(
  "content_plans",
  {
    id: text("id").primaryKey(),
    projectId: text("project_id")
      .notNull()
      .references(() => projects.id, { onDelete: "cascade" }),
    enabled: integer("enabled", { mode: "boolean" })
      .notNull()
      .default(false),
    cadencePerWeek: integer("cadence_per_week").notNull().default(3),
    // How long an autopilot draft waits before auto-publishing. 0 = publish
    // immediately (no window).
    reviewWindowHours: integer("review_window_hours").notNull().default(72),
    autoPublish: integer("auto_publish", { mode: "boolean" })
      .notNull()
      .default(true),
    // Winnability floors for discovered topics.
    minSearchVolume: integer("min_search_volume").notNull().default(50),
    maxDifficulty: integer("max_difficulty").notNull().default(40),
    // Public URL template for the customer's blog, e.g.
    // "https://example.com/blog/{slug}". Drives each article's liveUrl for GSC
    // tracking. Null until the user sets it.
    blogUrlPattern: text("blog_url_pattern"),
    lastPlannedAt: text("last_planned_at"),
    // When the next scheduled auto-generation is due; advanced by the cron.
    nextRunAt: text("next_run_at"),
    createdAt: text("created_at")
      .notNull()
      .default(sql`(current_timestamp)`),
    updatedAt: text("updated_at")
      .notNull()
      .default(sql`(current_timestamp)`),
  },
  (table) => [
    uniqueIndex("content_plans_project_idx").on(table.projectId),
    // Cron scans for enabled plans that are due.
    index("content_plans_next_run_idx").on(table.enabled, table.nextRunAt),
  ],
);

// A topic cluster: one pillar article and its satellites, linked bidirectionally.
export const contentClusters = sqliteTable(
  "content_clusters",
  {
    id: text("id").primaryKey(),
    projectId: text("project_id")
      .notNull()
      .references(() => projects.id, { onDelete: "cascade" }),
    name: text("name").notNull(),
    // The pillar article for this cluster (no FK to avoid a circular reference
    // with content_articles.cluster_id).
    pillarArticleId: text("pillar_article_id"),
    createdAt: text("created_at")
      .notNull()
      .default(sql`(current_timestamp)`),
  },
  (table) => [index("content_clusters_project_idx").on(table.projectId)],
);

// The discovered-topic queue and editorial calendar. A topic moves
// suggested → scheduled → generating → generated (or dismissed).
export const contentTopics = sqliteTable(
  "content_topics",
  {
    id: text("id").primaryKey(),
    projectId: text("project_id")
      .notNull()
      .references(() => projects.id, { onDelete: "cascade" }),
    clusterId: text("cluster_id"),
    keyword: text("keyword").notNull(),
    // Where the topic came from: GSC opportunity or keyword expansion.
    source: text("source", { enum: ["gsc", "expansion"] }).notNull(),
    role: text("role", { enum: ["pillar", "satellite"] })
      .notNull()
      .default("satellite"),
    searchVolume: integer("search_volume"),
    difficulty: integer("difficulty"),
    status: text("status", {
      enum: ["suggested", "scheduled", "generating", "generated", "dismissed"],
    })
      .notNull()
      .default("suggested"),
    // Calendar slot (YYYY-MM-DD) once scheduled.
    scheduledFor: text("scheduled_for"),
    // The article generated for this topic, once it exists.
    articleId: text("article_id"),
    createdAt: text("created_at")
      .notNull()
      .default(sql`(current_timestamp)`),
    updatedAt: text("updated_at")
      .notNull()
      .default(sql`(current_timestamp)`),
  },
  (table) => [
    index("content_topics_project_status_idx").on(
      table.projectId,
      table.status,
    ),
    index("content_topics_scheduled_idx").on(table.scheduledFor),
    // Avoid queuing the same keyword twice for a project.
    uniqueIndex("content_topics_project_keyword_idx").on(
      table.projectId,
      table.keyword,
    ),
  ],
);

// ---------------------------------------------------------------------------
// Phase 3 — per-article GSC performance snapshots for the journey timeline
// and the weekly self-repair loop.
// ---------------------------------------------------------------------------

export const contentArticleMetrics = sqliteTable(
  "content_article_metrics",
  {
    id: text("id").primaryKey(),
    articleId: text("article_id")
      .notNull()
      .references(() => contentArticles.id, { onDelete: "cascade" }),
    // Snapshot date (YYYY-MM-DD); one row per article per day.
    date: text("date").notNull(),
    clicks: integer("clicks").notNull().default(0),
    impressions: integer("impressions").notNull().default(0),
    ctr: real("ctr").notNull().default(0),
    position: real("position").notNull().default(0),
    createdAt: text("created_at")
      .notNull()
      .default(sql`(current_timestamp)`),
  },
  (table) => [
    uniqueIndex("content_article_metrics_article_date_idx").on(
      table.articleId,
      table.date,
    ),
  ],
);

// Bearer keys for the public headless content API. Only the SHA-256 hash is
// stored; the plaintext key is shown once at creation.
export const contentApiKeys = sqliteTable(
  "content_api_keys",
  {
    id: text("id").primaryKey(),
    projectId: text("project_id")
      .notNull()
      .references(() => projects.id, { onDelete: "cascade" }),
    keyHash: text("key_hash").notNull(),
    label: text("label").notNull(),
    createdAt: text("created_at")
      .notNull()
      .default(sql`(current_timestamp)`),
    lastUsedAt: text("last_used_at"),
    revokedAt: text("revoked_at"),
  },
  (table) => [
    uniqueIndex("content_api_keys_key_hash_idx").on(table.keyHash),
    index("content_api_keys_project_idx").on(table.projectId),
  ],
);
